config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users

  namespace :seller do
    resources :products do 
      collection do 
        post :ordered_product
      end
    end
  end

  root to: 'dashboards#index'

  devise_for :sellers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :products do
    collection do 
     post :user_ordered_product
    end
  end
  resources :sellers
  resources :dashboards
  
resources :cards do
  collection do 
    post :remove_item
    post :order
  end
end

  namespace :admin do
    resources :products
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  belongs_to :user
  # has_many :card_items
  has_many :items, as: :itemable
  has_many :products, through: :items, source: :product

  def product_present(product)
    card_item = items.find_by_product_id(product.id)
    unless card_item.nil?

      card_item.quantity += 1
      card_item.save
    end
  end
end

app/models/card_item.rb
class CardItem < ApplicationRecord
	belongs_to :card
	belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :itemable, polymorphic: true
  belongs_to :product
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :items, as: :itemable
end

app/models/product.rb
class Product < ApplicationRecord

	belongs_to :seller
	belongs_to :category
	has_one_attached :image
end

app/models/seller.rb
# frozen_string_literal: true

class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :categories

  def show_ordered_product(seller)
    Item.joins(product: :seller).where(products: { seller_id: seller.id })
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :card
  has_many :orders

  def order_product
    orders = self.orders
    orders.map { |order| order.items.where(itemable_id: order.id) }.flatten
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # before_action :authenticate_seller!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_card
    if current_user.card
      current_user.card
    else
      card = current_user.build_card
      card.save
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address number])
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  def index
    @cards = current_card
  end

  def create
    current_card
    add_to_item
    flash[:notice] = 'The cart is created and ,you have insert the item successfully'
    redirect_to(cards_path) and return
  end

  def remove_item
    card_item = Item.find(params[:item_id])
    if card_item.quantity > 1
      card_item.quantity -= 1
      card_item.save
    elsif card_item.quantity == 1
      card_item.destroy
      card_item.save
    end
    redirect_to(cards_path) and return
  end

  def order
    order = Order.create(order_params)
    if order.save
      card = current_card
      card.items.update(itemable_id: order.id, itemable_type: 'Order')
      flash[:notice] = 'you have ordered successfully'
      redirect_to(dashboards_path) and return
    else
      flash[:notice] = 'Please check order is not created'
      redirect_to(cards_path) and return
    end
  end

  private

  def add_to_item
    card = current_card
    product = Product.find(params[:product_id])
    return if card.product_present(product)

    card.items.create(product_id: params[:product_id], quantity: 1)
  end

  def order_params
    params.require(:order).permit(:user_id, :mobile, :address)
  end
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def index
    @products = if seller_signed_in?
                  current_seller.products
                else
                  Product.all
                end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @product = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def user_ordered_product
    user = current_user
    @order_product = user.order_product
  end
end

app/helpers/add_to_cart_helper.rb
module AddToCartHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin_products_helper.rb
module AdminProductsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def total_price
    card = current_user.card
    card.items.sum { |p| p.product.price * p.quantity }
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/seller/products_helper.rb
module Seller::ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/cards/_order_form.html.erb
<!-- Modal -->
<div class="modal fade" id="pop-custom"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
 <%= form_for(Order.new, url: order_cards_path, remote: true, method: :post) do |f| %>

  <div class="field">
    <%= f.label :Mobile_number %><br />
    <%= f.text_field :mobile %>
    <%= f.hidden_field :user_id , value: user_id %>
  </div>

  <div class="field">
    <%= f.label :Address %><br />
    <%= f.text_field :address %>
  </div>
     
  <div class="modal-footer"><br>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "place order", class: "btn btn-primary" %>
  <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cards/index.html.erb
<!-- <p> hello soon will show product</p> -->
<h3> Listing selected product </h3>

<div class="card" style="width: 20rem;">
  <% @cards.items.each do |card_item| %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><%= card_item.product.name %>
                                    <%= card_item.product.price %>
                                    <%= image_tag(card_item.product.image.variant(resize_to_limit: [60, 60])) if card_item.product.image.attached? %>
                                     Qty:&nbsp<%= card_item.quantity %>
                                     &nbsp<%= link_to 'Remove item', remove_item_cards_path(:item_id => card_item), method: :post, :class => "btn btn-default"%>
      </li>
    </ul>
  <% end %>
</div>

<br>
<div class="card border-secondary mb-3" style="max-width: 18rem;">
  <div class="card-header bg-transparent border-secondary">PRICE DETAILS</div>
    <p class="card-text">The  total item is => <%= @cards.items.size %></p>
  <div class="card-footer bg-transparent border-secondary">Total Amount =>
      <%= total_price %>
  </div>
</div>

<%= link_to "Order now", "javascript:void(0)",  :class => "btn btn-primary" , id: "order"%>
 <%= render partial: "order_form", locals: { user_id: @cards.user.id }%>

<div id="popcontent"></div>

<script type="text/javascript">
  $(document).ready ( function () {
    $("#order").click(function(){
     $('#pop-custom').modal('show');
    });
  });
</script>

app/views/dashboards/index.html.erb
<%= render partial: 'seller/products/seller_menu'%>
<% if seller_signed_in? %>
  <%= render partial: 'seller/products/seller_products'%>
<% elsif user_signed_in? %>
  <%= render partial: 'products/show_products'%>
<% else %>
  <%= render partial: 'products/show_products'%>
<% end %>