config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users

  namespace :seller do
    resources :products do 
      collection do 
        post :ordered_product
      end
    end
  end

  root to: 'dashboards#index'

  devise_for :sellers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :products do
    collection do 
     post :user_ordered_product
    end
  end
  resources :sellers
  resources :dashboards
  
resources :cards do
  collection do 
    post :remove_item
    post :order
  end
end

  namespace :admin do
    resources :products
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  belongs_to :user
  # has_many :card_items
  has_many :items, as: :itemable
  has_many :products, through: :items, source: :product

  def product_present(product)
    card_item = items.find_by_product_id(product.id)
    unless card_item.nil?

      card_item.quantity += 1
      card_item.save
    end
  end
end

app/models/card_item.rb
class CardItem < ApplicationRecord
	belongs_to :card
	belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :itemable, polymorphic: true
  belongs_to :product
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :items, as: :itemable
end

app/models/product.rb
class Product < ApplicationRecord

	belongs_to :seller
	belongs_to :category
	has_one_attached :image
end

app/models/seller.rb
# frozen_string_literal: true

class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :categories

  def show_ordered_product(seller)
    Item.joins(product: :seller).where(products: { seller_id: seller.id })
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :card
  has_many :orders

  def order_product
    orders = self.orders
    orders.map { |order| order.items.where(itemable_id: order.id) }.flatten
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  
  


end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # before_action :authenticate_seller!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_card
    if current_user.card
      current_user.card
    else
      card = current_user.build_card
      card.save
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address number])
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  def index
    @cards = current_card
  end

  def create
    current_card
    add_to_item
    flash[:notice] = 'The cart is created and ,you have insert the item successfully'
    redirect_to(cards_path) and return
  end

  def remove_item
    card_item = Item.find(params[:item_id])
    if card_item.quantity > 1
      card_item.quantity -= 1
      card_item.save
    elsif card_item.quantity == 1
      card_item.destroy
      card_item.save
    end
    redirect_to(cards_path) and return
  end

  def order
    order = Order.create(order_params)
    if order.save
      card = current_card
      card.items.update(itemable_id: order.id, itemable_type: 'Order')
      flash[:notice] = 'you have ordered successfully'
      redirect_to(dashboards_path) and return
    else
      flash[:notice] = 'Please check order is not created'
      redirect_to(cards_path) and return
    end
  end

  private

  def add_to_item
    card = current_card
    product = Product.find(params[:product_id])
    return if card.product_present(product)

    card.items.create(product_id: params[:product_id], quantity: 1)
  end

  def order_params
    params.require(:order).permit(:user_id, :mobile, :address)
  end
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def index
    @products = if seller_signed_in?
                  current_seller.products
                else
                  Product.all
                end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @product = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def user_ordered_product
    user = current_user
    @order_product = user.order_product
  end
end

app/controllers/seller/products_controller.rb
class Seller::ProductsController < ApplicationController 
  def index
    @products = current_seller.products
  end

  def create
    @product = current_seller.products.create(product_params)
    @product.save
    redirect_to seller_products_path
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to seller_products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to seller_products_path
  end

   def ordered_product
    @seller = current_seller
    @seller_products = @seller.show_ordered_product(@seller)
   end

private
   def product_params
    params.require(:product).permit(:name,:description,:price,:category_id,:image)
   end
end

app/helpers/add_to_cart_helper.rb
module AddToCartHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin_products_helper.rb
module AdminProductsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def total_price
    card = current_user.card
    card.items.sum { |p| p.product.price * p.quantity }
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/seller/products_helper.rb
module Seller::ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/admin/products/index.html.erb
<h1>Its Admin section</h1>

app/views/products/_show_products.html.erb
<div class="container pt-5" > 
<% @products.each_slice(3) do |products| %>      
    <div class="row row-cols-1 row-cols-md-3"> 
      <% products.each do |product| %>
         <div class="card" style="width: 21rem;margin: 10px 10px;">
                <a href="<%= product_path(product) %>">
                <%= image_tag(product.image , :class=> "card-img-top", :style=> "margin: 10px 10px 10px 10px;height: 100%") if product.image.attached?  %>  </a> 
            <div class="card-body">
                <p class="card-text"> <%=product.name %></p> 
                <p class="card-text"> <%=product.price %></p>
            </div>
        </div>
      <% end %>                        
    </div>
<% end %>
</div>

<!-- <div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div> -->

app/views/products/index.html.erb
<%= render partial: 'show_products' %>

app/views/products/show.html.erb
<div class="container">
	<div class="card" style="width: 19rem;margin: 30px 10px;">
	  <%= image_tag(@product.image , :class=> "card-img-top", :style=> "margin: 10px 10px 10px 10px;height: 100%") if @product.image.attached?  %>  
	  	<div class="card-body">
		    <p class="card-text"> Name: <%= @product.name %></p> 
		    <p class="card-text"> Description: <%= @product.description %></p> 
		    <p class="card-text"> price: <%= @product.price%></p> 
		    <p class="card-text"> Seller: <%= @product.seller.first_name %></p> 
		    <p class="card-text"> Category: <%= @product.category.name%></p> 
	 		</div>
	</div>		   
	 <%= link_to "Add to card", cards_path(:product_id => @product), method: :post, :class => "btn btn-primary" %> <br>

	 <br><%= link_to "Back", dashboards_path ,:class => "btn btn-primary" %>
</div>

app/views/products/user_ordered_product.html.erb
<div class="modal-body">    
	<div class="container pt-5" >
			<table class="table table-striped ">                         
				<tr>                          
				  <th scope="col">name</th>
				  <th scope="col">price</th>
				  <th scope="col">Image</th>
				  <th scope="col">Quantity</th>
				  </tr>
			    <% @order_product.map do |order_product| %>
				    <tr>
					    <td ><%= order_product.product.name %> </td>  
					    <td><%= order_product.product.price %></td>  
					    <td><%= image_tag(order_product.product.image.variant(resize_to_limit: [60, 60])) if order_product.product.image.attached? %></td> 
					    <td><%= order_product.quantity %></td>  
					    <td></td>
					  </tr>
				  <% end %>                        
				</table>
			</div>
	</div>
</div>

app/views/seller/products/_seller_menu.html.erb
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <!-- Brand -->
  <a class="navbar-brand" href="#">Logo</a>
  <!-- Links -->
  <ul class="navbar-nav ">
    <li class="nav-item">
      <a class="nav-link" href="#">Link 2</a>
    </li>
  <% unless seller_signed_in? %>
    <!-- Dropdown -->
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Other
          </a>
          <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><%= link_to "seller login", new_seller_session_path, :class => "dropdown-item" %> </li>
          </ul>
        </li>
      </ul>
  </ul>
  <% end %>

  <ul class="navbar-nav">
    <% if seller_signed_in? %>
    <li class="nav-item">
      <%= link_to 'signout', destroy_seller_session_path, :class => "btn btn-primary " ,method: :delete %>
    </li>
    <% elsif user_signed_in? %>
    <li class="nav-item">
      <%= link_to 'signout', destroy_user_session_path, :class => "btn btn-primary " ,method: :delete %>
      <%= link_to 'My order', user_ordered_product_products_path, method: :post ,:class => "btn btn-primary "  %>
    </li>
    <% else %>
    <li class="nav-item">
      <%= link_to "login", new_user_session_path, :class => "btn btn-primary "%>
    </li>
    <% end %>
  </ul>
</nav>






    

app/views/seller/products/_seller_ordered_product.html.erb
<!-- Modal -->
<div class="modal fade" id="pop-custom"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content " style= "width:135%;  ">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ordered Product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <div class="modal-body">    
	 		<div class="container pt-5" >
				<table class="table table-striped ">                         
				  <tr>                          
				    <th scope="col">name</th>
				    <th scope="col">description</th>
				    <th scope="col">price</th>
				    <th scope="col">category</th>
				    <th scope="col">Image</th>
				    <th scope="col">Quantity</th>
				    <th scope="col">user</th>
				  </tr>
			    <% seller_products.map do |seller_product| %>
				    <tr>
					    <td ><%= seller_product.product.name %> </td>  
					    <td><%= seller_product.product.description%></td>  
					    <td><%= seller_product.product.price %></td>  
					    <td><%= seller_product.product.category.name %></td> 
					    <td><%= image_tag(seller_product.product.image.variant(resize_to_limit: [60, 60])) if seller_product.product.image.attached? %></td> 
					    <td><%= seller_product.quantity %></td> 
					    <td> <%= seller_product.itemable.user.email %></td>
					    <td></td>
					  </tr>
				  <% end %>                        
				</table>
			 </div>
	    </div>
	  </div>
	</div>
</div>

app/views/seller/products/_seller_products.html.erb
<%= render partial: 'seller/products/sidebar'%>
<div class="container pt-5" >
<table class="table table-striped ">                         
  <tr>                          
    <th scope="col">name</th>
    <th scope="col">description</th>
    <th scope="col">price</th>
    <th scope="col">category</th>
    <th scope="col">Image</th>
    <th scope="col">option</th>
  </tr>
<% @products.each do |product| %>
  <tr>
    <td ><%=product.name %> </td>  
    <td><%= product.description%></td>  
    <td><%= product.price %></td>  
    <td><%= product.category.name %></td> 
    <td><%= image_tag(product.image.variant(resize_to_limit: [60, 60])) if product.image.attached? %></td> 
    <td>
      <div class="btn-group" role="group" aria-label="...">
      <%= link_to 'Edit', edit_seller_product_path(product), :class => "btn btn-default"%>
      <%= link_to 'Delete', [:seller,product], method: 'delete', :class => "btn btn-default "%>
        
    </div>
      </td> 
  </tr>
<% end %>                        
</table>
</div>

app/views/seller/products/_sidebar.html.erb
<nav class="navbar1 navbar-expand d-flex flex-column align-item-start" id="sidebar">
   <ul class="navbar-nav d-flex flex-column mt-5 w-100">
        <li><%= link_to "Add new product", new_seller_product_path, :class => "nav-item w-150 nav-link1 text-dark pl-4" %> </li>
   </ul>

   <ul class="navbar-nav d-flex flex-column mt-5 w-100">
        <li><%= link_to "Orders",  ordered_product_seller_products_path,method: :post, remote: true, :class => "nav-item w-150 nav-link1 text-dark pl-4" %> </li>
   </ul>
</nav>

<div id="ordered_product"></div>

app/views/seller/products/edit.html.erb
 <h1>Edit Product </h1>

 <%= form_for [:seller, @product] do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category_id, options_from_collection_for_select(Category.all, "id", "name") %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>

   
  <div class="actions">
    <%= f.submit "edit product" %>
  </div>

  <% end %> 

app/views/seller/products/index.html.erb
<%= render partial: 'seller_menu'%>

<%= render partial: 'seller_products'%>

app/views/seller/products/new.html.erb
<h1>New Product</h1>


 <%= form_for [:seller, @product] do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category_id, options_from_collection_for_select(Category.all, "id", "name") %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>

   
  <div class="actions">
    <%= f.submit "create product" %>
  </div>

  <% end %> 

app/views/seller/products/ordered_product.js.erb
$("#ordered_product").html("<%= escape_javascript(render partial: "seller/products/seller_ordered_product", locals: { seller_products: @seller_products }) %>");
$('#pop-custom').modal('show');

app/views/sellers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/sellers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>